Shopping/Shopping/Models/CityViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Shopping.Models
{
    public class CityViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Ciuadad")]
        [MaxLength(50, ErrorMessage = "El campo {0} debe tener máximo {1} caractéres.")]
        [Required(ErrorMessage = "El campo {0} es obligatorio.")]
        public string Name { get; set; }

        public int StateId { get; set; }
    }
}

Shopping/Shopping/Models/StateViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Shopping.Models
{
    public class StateViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Departamento/Estado")]
        [MaxLength(50, ErrorMessage = "El campo {0} debe tener máximo {1} caractéres.")]
        [Required(ErrorMessage = "El campo {0} es obligatorio.")]
        public string Name { get; set; }

        public int CountryId { get; set; }
    }
}

Shopping/Shopping/Controllers/CountriesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Shopping.Data;
using Shopping.Data.Entities;
using Shopping.Helpers;
using Shopping.Models;
using Vereyon.Web;
using static Shopping.Helpers.ModalHelper;

namespace Shopping.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CountriesController : Controller
    {
        private readonly DataContext _context;
        private readonly IFlashMessage _flashMessage;

        public CountriesController(DataContext context, IFlashMessage flashMessage)
        {
            _context = context;
            _flashMessage = flashMessage;
        }

        // GET: Countries
        public async Task<IActionResult> Index()
        {
            //return View(await _context.Countries.ToListAsync());
            return View(await _context.Countries
                .Include(c => c.States)
                .ThenInclude(s => s.Cities)
                .ToListAsync());
        }

        // GET: Countries/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Country country = await _context.Countries
                .Include(c => c.States)
                .ThenInclude(s => s.Cities)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (country == null)
            {
                return NotFound();
            }

            return View(country);
        }

        //public IActionResult Create()
        //{
        //    Country country = new() { States = new List<State>() };
        //    return View(country);
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create(Country country)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Add(country);
        //            await _context.SaveChangesAsync();
        //            return RedirectToAction(nameof(Index));
        //        }
        //        catch (DbUpdateException dbUpdateException)
        //        {
        //            if (dbUpdateException.InnerException.Message.Contains("duplicada"))
        //            {
        //                ModelState.AddModelError(string.Empty, "Ya existe un país con el mismo nombre.");
        //            }
        //            else
        //            {
        //                ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
        //            }
        //        }
        //        catch (Exception exception)
        //        {
        //            ModelState.AddModelError(string.Empty, exception.Message);
        //        }


        //    }
        //    return View(country);
        //}

        [NoDirectAccess]
        public async Task<IActionResult> AddState(int id)
        {
            
            Country country = await _context.Countries.FindAsync(id);
            if (country == null)
            {
                return NotFound();
            }

            StateViewModel model = new()
            {
                CountryId = country.Id,
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddState(StateViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    State state = new()
                    {
                        Cities = new List<City>(),
                        Country = await _context.Countries.FindAsync(model.CountryId),
                        Name = model.Name,
                    };
                    _context.Add(state);
                    await _context.SaveChangesAsync();
                    Country country = await _context.Countries
                        .Include(c => c.States)
                        .ThenInclude(s => s.Cities)
                        .FirstOrDefaultAsync(c => c.Id == model.CountryId);
                    _flashMessage.Info("Registro creado.");
                    return Json(new { isValid = true, html = ModalHelper.RenderRazorViewToString(this, "_ViewAllStates", country) });

                }
                catch (DbUpdateException dbUpdateException)
                {
                    if (dbUpdateException.InnerException.Message.Contains("duplicada"))
                    {
                        ModelState.AddModelError(string.Empty, "Ya existe un departamento/estado con el mismo nombre en este país.");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
                    }
                }
                catch (Exception exception)
                {
                    ModelState.AddModelError(string.Empty, exception.Message);
                }
            }

            return Json(new { isValid = false, html = ModalHelper.RenderRazorViewToString(this, "AddState", model) });
        }

        [NoDirectAccess]
        public async Task<IActionResult> EditState(int id)
        {
           
            State state = await _context.States
                .Include(s => s.Country)
                .FirstOrDefaultAsync(s => s.Id == id);
            if (state == null)
            {
                return NotFound();
            }

            StateViewModel model = new()
            {
                CountryId = state.Country.Id,
                Id = state.Id,
                Name = state.Name,
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditState(int id, StateViewModel model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    State state = new()
                    {
                        Id = model.Id,
                        Name = model.Name,
                    };
                    _context.Update(state);
                    Country country = await _context.Countries
                        .Include(c => c.States)
                        .ThenInclude(s => s.Cities)
                        .FirstOrDefaultAsync(c => c.Id == model.CountryId);
                    await _context.SaveChangesAsync();
                    _flashMessage.Confirmation("Registro actualizado.");
                    return Json(new { isValid = true, html = ModalHelper.RenderRazorViewToString(this, "_ViewAllStates", country) });
                }
                catch (DbUpdateException dbUpdateException)
                {
                    if (dbUpdateException.InnerException.Message.Contains("duplicada"))
                    {
                        ModelState.AddModelError(string.Empty, "Ya existe un Departamento / Estado con el mismo nombre en este país.");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
                    }
                }
                catch (Exception exception)
                {
                    ModelState.AddModelError(string.Empty, exception.Message);
                }
            }

            return Json(new { isValid = false, html = ModalHelper.RenderRazorViewToString(this, "EditState", model) });
        }
        public async Task<IActionResult> DetailsState(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            State state = await _context.States
                .Include(s => s.Country)
                .Include(s => s.Cities)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (state == null)
            {
                return NotFound();
            }

            return View(state);
        }

        [NoDirectAccess]
        public async Task<IActionResult> AddCity(int id)
        {
            
            State state = await _context.States.FindAsync(id);
            if (state == null)
            {
                return NotFound();
            }

            CityViewModel model = new()
            {
                StateId = state.Id,
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddCity(CityViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    City city = new()
                    {
                        State = await _context.States.FindAsync(model.StateId),
                        Name = model.Name,
                    };
                    _context.Add(city);
                    await _context.SaveChangesAsync();
                    State state = await _context.States
                        .Include(s => s.Cities)
                        .FirstOrDefaultAsync(c => c.Id == model.StateId);
                    _flashMessage.Confirmation("Registro creado.");
                    return Json(new { isValid = true, html = ModalHelper.RenderRazorViewToString(this, "_ViewAllCities", state) });
                }
                catch (DbUpdateException dbUpdateException)
                {
                    if (dbUpdateException.InnerException.Message.Contains("duplicada"))
                    {
                        ModelState.AddModelError(string.Empty, "Ya existe una ciudad con el mismo nombre en este Departamento / Estado.");
                    }

Shopping/Shopping/Views/Countries/AddCity.cshtml
@model Shopping.Models.CityViewModel

@{
    ViewData["Title"] = "Ciuadad";
    Layout = null;
}

<flash dismissable="true" />

<div class="container smfont">
    <form asp-action="AddCity" autocomplete="off" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPost(this);">
        <div class="box-body">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="StateId" />
            <partial name="_City" />
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-sm btn-primary" data-bs-dismiss="modal"><i class="fa fa-ban"></i> Cancelar</button>
            <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-save"></i> Guardar</button>
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Shopping/Shopping/Views/Countries/AddOrEdit.cshtml
@model Shopping.Data.Entities.Country

@{
    ViewData["Title"] = "País";
    Layout = null;
}

<flash dismissable="true" />

<div class="container smfont">
    <form asp-action="AddOrEdit" autocomplete="off" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPost(this);">
        <div class="box-body">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <span class="required">*</span>
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control smfont" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-sm btn-primary" data-bs-dismiss="modal"><i class="fa fa-ban"></i> Cancelar</button>
            <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-save"></i> Guardar</button>
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Shopping/Shopping/Views/Countries/AddState.cshtml
@model Shopping.Models.StateViewModel

@{
    ViewData["Title"] = "Estado / Departamento";
    Layout = null;
}

<flash dismissable="true" />

<div class="container smfont">
    <form asp-action="AddState" autocomplete="off" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPost(this);">
        <div class="box-body">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CountryId" />
            <partial name="_State" />
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-sm btn-primary" data-bs-dismiss="modal"><i class="fa fa-ban"></i> Cancelar</button>
            <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-save"></i> Guardar</button>
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Shopping/Shopping/Views/Countries/DeleteCity.cshtml
@model Shopping.Data.Entities.City

@{
    ViewData["Title"] = "Delete";
}
<flash dismissable="true" />
<h1>Borrar</h1>

<h3>¿Esta seeguro de querer borrar?</h3>
<div>
    <partial name="_CityDetails"/>    
    <form asp-action="DeleteCity">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Borrar" class="btn btn-outline-danger" />
        <a asp-action="DetailsState" asp-route-id="@Model?.State.Id" class="btn btn-outline-success">Regresar</a>
    </form>
</div>

Shopping/Shopping/Views/Countries/Details.cshtml
@model Shopping.Data.Entities.Country

@{
    ViewData["Title"] = "Details";
}

<link rel="stylesheet" href="//cdn.datatables.net/responsive/2.2.6/css/responsive.dataTables.min.css" />

<flash dismissable="true" />

<h1>Detalles</h1>

<div>
    <partial name="_CountryDetails" />    
</div>

<div>
    <a asp-action="Index" class="btn btn-outline-success"><i class="fa-solid fa-arrow-rotate-left"></i> Regresar</a>
</div>
<hr />

<!-- Content Wrapper. Contains page content -->
<div class="container-fluid">
    <div class="card mt-2">
        <div class="card-header text-danger">
            <i class="fa fa-globe"></i>  <strong>Estados / Departamentos</strong>
        </div>
        <div class="card-body">
            <div id="view-all">
                @await Html.PartialAsync("_ViewAllStates", Model)
            </div>
        </div>
    </div>
</div>

<partial name="_AddOrEditDialog" />
<partial name="_DeleteDialog" />

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="//cdn.datatables.net/responsive/2.2.6/js/dataTables.responsive.min.js"></script>
    <script src="~/js/showmodal.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#StatesTable').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                },
                "aLengthMenu": [
                    [25, 50, 100, 200, -1],
                    [25, 50, 100, 200, "Todos"]
                ]
            });
        });
    </script>

    <script>
        sc_deleteDialog.openModal('deleteItem', true, 'btnYesDelete', '/Countries/DeleteState/', false);
    </script>
}

Shopping/Shopping/Views/Countries/DetailsState.cshtml
@model Shopping.Data.Entities.State


@{
    ViewData["Title"] = "Details";
}

<flash dismissable="true" />

<h1>Detalles</h1>

<div>
    <partial name="_StateDetails" />    
</div>

<div>
    <a asp-action="Details" asp-route-id="@Model?.Country.Id" class="btn btn-outline-success"><i class="fa-solid fa-arrow-rotate-left"></i> Regresar</a>
</div>
<hr />

<!-- Content Wrapper. Contains page content -->
<div class="container-fluid">
    <div class="card mt-2">
        <div class="card-header text-danger">
            <i class="fa fa-object-group"></i>  <strong>Estados / Departamentos</strong>
        </div>
        <div class="card-body">
            <div id="view-all">
                @await Html.PartialAsync("_ViewAllCities", Model)
            </div>
        </div>
    </div>
</div>

<!--modal placeholder. Also you can place this modal form in the _Layout.cshtml-->

<partial name="_AddOrEditDialog" />
<partial name="_DeleteDialog" />

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="~/js/showmodal.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#StatesTable').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                },
                "aLengthMenu": [
                    [25, 50, 100, 200, -1],
                    [25, 50, 100, 200, "Todos"]
                ]
            });
        });
    </script>

    <script>
        sc_deleteDialog.openModal('deleteItem', true, 'btnYesDelete', '/Countries/DeleteCity/', false);
    </script>
}

Shopping/Shopping/Views/Countries/EditState.cshtml
@model Shopping.Models.StateViewModel

@{
    ViewData["Title"] = "Estado / Departamento";
    Layout = null;
}

<flash dismissable="true" />

<div class="container smfont">
    <form asp-action="EditState" autocomplete="off" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPost(this);">
        <div class="box-body">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="CountryId" />
            <partial name="_State"/>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-sm btn-primary" data-bs-dismiss="modal"><i class="fa fa-ban"></i> Cancelar</button>
            <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-save"></i> Guardar</button>
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Shopping/Shopping/Views/Countries/Index.cshtml
@model IEnumerable<Shopping.Data.Entities.Country>

@{
    ViewData["Title"] = "Index";
}
<flash dismissable="true" />
@*<h1>Paises</h1>*@

<link rel="stylesheet" href="//cdn.datatables.net/responsive/2.2.6/css/responsive.dataTables.min.css" />

<!-- Content Wrapper. Contains page content -->
<div class="container-fluid">
    <div class="card mt-2">
        <div class="card-header text-danger">
            <i class="fa fa-globe"></i>  <strong>Países</strong>
        </div>
        <div class="card-body">
            <div id="view-all">
                @await Html.PartialAsync("_ViewAll", Model)
            </div>
        </div>
    </div>
</div>

<partial name="_AddOrEditDialog" />
<partial name="_DeleteDialog" />

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="//cdn.datatables.net/responsive/2.2.6/js/dataTables.responsive.min.js"></script>
    <script src="~/js/showmodal.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#CountriesTable').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                },
                "aLengthMenu": [
                    [25, 50, 100, 200, -1],
                    [25, 50, 100, 200, "Todos"]
                ]
            });
        });
    </script>

    <script>
        sc_deleteDialog.openModal('deleteItem', true, 'btnYesDelete', '/Countries/Delete/', false);
    </script>
}

Shopping/Shopping/Views/Countries/_City.cshtml
@model Shopping.Models.CityViewModel

<div class="form-group">
     <span class="required">*</span>
    <label asp-for="Name" class="control-label"></label>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
</div>

Shopping/Shopping/Views/Countries/_CityDetails.cshtml
@model Shopping.Data.Entities.City

<h4>Ciudad</h4>
<hr />
<dl class="row">
    <dt class = "col-sm-2">
        @Html.DisplayNameFor(model => model.Name)
    </dt>
    <dd class = "col-sm-10">
        @Html.DisplayFor(model => model.Name)
    </dd>
</dl>

Shopping/Shopping/Views/Countries/_CountryDetails.cshtml
@model Shopping.Data.Entities.Country

<h4>Pais</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
        @Html.DisplayNameFor(model => model.StatesNumber)
    </dt>
    <dd class = "col-sm-10">
        @Html.DisplayFor(model => model.StatesNumber)
    </dd>
    </dl>

Shopping/Shopping/Views/Countries/_State.cshtml
@model Shopping.Models.StateViewModel

<div class="form-group">
    <span class="required">*</span>
    <label asp-for="Name" class="control-label"></label>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
</div>

Shopping/Shopping/Views/Countries/_ViewAllCities.cshtml
@model Shopping.Data.Entities.State

<flash dismissable="true" />

<table class="table table-striped table-responsive-md table-bordered smfont"  id="StatesTable">
    <colgroup>
        <col span="1" />
        <col span="1" />
    </colgroup>
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Cities.FirstOrDefault().Name)
            </th>
            <th>
                <a onclick="showInPopup('@Url.Action("AddCity", "Countries", new { id = Model.Id }, Context.Request.Scheme)' , 'Nueva Ciudad')" class="btn btn-sm btn-primary text-white"><i class="fa fa-plus-circle"></i> Ciudad</a>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Cities)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a onclick="showInPopup('@Url.Action("EditCity", "Countries", new { id = item.Id }, Context.Request.Scheme)' , 'Actualizar Ciudad')" class="btn btn-sm btn-warning"><i class="fa fa-pencil-alt"></i> </a>
                <button data-id="@item.Id" class="btn btn-sm btn-danger deleteItem" data-bs-toggle="modal" data-bs-target="#deleteDialog"><i class="fa fa-trash"></i></button>
            </td>
        </tr>
        }
    </tbody>
</table>

Shopping/Shopping/Views/Countries/_ViewAllStates.cshtml
@model Shopping.Data.Entities.Country

<flash dismissable="true" />

<table class="table table-hover display responsive nowrap" style="width:100%"  id="StatesTable">
    <colgroup>
        <col span="1" />
        <col span="1" />
    </colgroup>
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.States.FirstOrDefault().Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.States.FirstOrDefault().CitiesNumber)
            </th>
            <th>
                <a onclick="showInPopup('@Url.Action("AddState", "Countries", new { id = Model?.Id }, Context.Request.Scheme)' , 'Nuevo Estado / Departamento')" class="btn btn-sm btn-primary text-white"><i class="fa fa-plus-circle"></i> Estado / Departamento</a>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model?.States)
        {
        <tr>
            <td>
                <a asp-action="DetailsState" asp-controller="Countries" asp-route-Id="@item.Id">@Html.DisplayFor(modelItem => item.Name)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CitiesNumber)
            </td>
            <td>
                <a onclick="showInPopup('@Url.Action("EditState", "Countries", new { id = item.Id }, Context.Request.Scheme)' , 'Actualizar Estado / Departamento')" class="btn btn-sm btn-warning"><i class="fa fa-pencil-alt"></i> </a>
                <button data-id="@item.Id" class="btn btn-sm btn-danger deleteItem" data-bs-toggle="modal" data-bs-target="#deleteDialog"><i class="fa fa-trash"></i></button>
            </td>
        </tr>
        }
    </tbody>
</table>